theme: jekyll-theme-minimal
title: 【変更可】Kurashicom Technology Group
description: 【変更可】私たちが大切にしている考えを書いています。
logo: https://s3-ap-northeast-1.amazonaws.com/qiita-organization-image/2b9a2acf98134ef3269fde0f70512f67bd906365/original.jpg?1536142056
show_downloads: false
